/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcchat.h"

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->operator, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, 255))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->timestamp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_historic (XDR *xdrs, historic *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->list.list_val, (u_int *) &objp->list.list_len, ~0,
		sizeof (message), (xdrproc_t) xdr_message))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
